---
name: cmpsc-101-fall-2018-practical3
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        practicalthree/BubbleSort.java:
            --multi 4 --language Java
            --fragment "println(" --count 4 --exact
# --> check the number of commits beyond a threshold
--commits 10
# --> check that the program executes and produces 20 lines of output
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 4 --exact
--command "gradle -q --console plain run" --fragment "F" --count 2 --exact
--command "gradle -q --console plain run" --fragment "4" --count 4 --exact
